import pygame
from pygame.sprite import Sprite

class Shockwave(Sprite):
	"""A class to manage shockwaves generated by explosions."""

	def __init__(self, hr_game, pos_x, pos_y, colour='white'):
		"""Create a shockwave at a specified origin point."""
		super().__init__()
		self.screen = hr_game.screen
		self.settings = hr_game.settings
		self.radius = self.settings.shockwave_radius
		self.border_width = self.settings.shockwave_border_width
		self.colour = colour
		self.pos_x = pos_x
		self.pos_y = pos_y

		# Define inputs needed to draw circle
		self.pos = (self.pos_x, self.pos_y)

	def update(self):
		"""Expand the radius of the circle whilst shrinking border width."""
		self.radius += 6
		self.border_width -= 0.1
				
	def draw_wave(self):
		"""Draw the wave using its current size/border"""
		pygame.draw.circle(self.screen, self.colour, self.pos,
					self.radius, int(self.border_width))